[package]
name = "rauth"
version = "0.2.0"
authors = ["Paul Makles <paulmakles@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snafu = { version = "0.6.9" }
validator = { version = "0.11", features = ["derive"] }
rocket_contrib = { git = "https://github.com/SergioBenitez/Rocket", branch = "master" }
rocket = { git = "https://github.com/SergioBenitez/Rocket", branch = "master", default-features = false }
serde = { version = "1.0.116", features = [ "derive" ] }
lazy_static = "1.4.0"
rust-argon2 = "0.8.2"
regex = "1.3.9"
tokio = "1"
mongodb = "1.1.1"
nanoid = "0.3.0"
json = "0.12.4"
chrono = "0.4.19"
lettre = "0.10.0-alpha.4"
ulid = "0.4.1"
