[package]
name = "rauth"
version = "0.1.0"
authors = ["Paul Makles <paulmakles@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snafu = "0.6.9"
rocket_contrib = { git = "https://github.com/SergioBenitez/Rocket" }
rocket = { git = "https://github.com/SergioBenitez/Rocket", default-features = false }
serde = { version = "1.0.116", features = [ "derive" ] }
validator = { version = "0.11", features = ["derive"] }
lazy_static = "1.4.0"
rust-argon2 = "0.8.2"
regex = "1.3.9"
tokio = "0.2.22"
mongodb = "1.1.1"
json = "0.12.4"
ulid = "0.4.1"
